poseapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from poseapp.views import hello_world, PoseCreateView, PoseDetailView

app_name = "poseapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', PoseCreateView.as_view(), name='create'),
    path('detail/<int:pk>', PoseDetailView.as_view(), name='detail'),

]

turtleneck/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pose/', include('poseapp.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poseapp/models.py
# from django.db import models
#
# # Create your models here.
#
#
# class Pose(models.Model):
#     image = models.ImageField(upload_to='pose/', null=False)
from os.path import dirname, join

from django.db import models
from .utils import output_keypoints, output_keypoints_with_lines
from PIL import Image
import numpy as np
from io import BytesIO
from django.core.files.base import ContentFile

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent


def rgba2rgb(rgba, background=(255, 255, 255)):
    row, col, ch = rgba.shape

    if ch == 3:
        return rgba

    assert ch == 4, 'RGBA image has 4 channels.'

    rgb = np.zeros((row, col, 3), dtype='float32')
    r, g, b, a = rgba[:, :, 0], rgba[:, :, 1], rgba[:, :, 2], rgba[:, :, 3]

    a = np.asarray(a, dtype='float32') / 255.0

    R, G, B = background

    rgb[:, :, 0] = r * a + (1.0 - a) * R
    rgb[:, :, 1] = g * a + (1.0 - a) * G
    rgb[:, :, 2] = b * a + (1.0 - a) * B

    return np.asarray(rgb, dtype='uint8')


# Create your models here.
class Pose(models.Model):
    image = models.ImageField(upload_to='image/', blank=True, null=True)

    def save(self, *args, **kwargs):
        # 이미지 열기
        pil_img = Image.open(self.image)

        # np array 변환
        cv_img = np.array(pil_img)
        cv_img = rgba2rgb(cv_img)
        # print(cv_img.shape)

        # cv_img = cv_img.reshape(-1, -1, -1)
        # 모델 위치
        # protoFile_body_25 = os.path.join(BASE_DIR, "model/pose_deploy.prototxt")
        # weightsFile_body_25 = os.path.join(BASE_DIR, "model/pose_iter_584000.caffemodel")
        protoFile_body_25 = "C:/Users/ohjoonhoo/Downloads/turtleneck/model/pose_deploy.prototxt"
        weightsFile_body_25 = "C:/Users/ohjoonhoo/Downloads/turtleneck/model/pose_iter_584000.caffemodel"
        # protoFile_body_25 = join(dirname(__file__), "model/pose_deploy.prototxt")
        # weightsFile_body_25 = join(dirname(__file__), "model/pose_iter_584000.caffemodel")

        BODY_PARTS_BODY_25 = {0: "Nose", 1: "Neck", 2: "RShoulder", 3: "RElbow", 4: "RWrist",
                              5: "LShoulder", 6: "LElbow", 7: "LWrist", 8: "MidHip", 9: "RHip",
                              10: "RKnee", 11: "RAnkle", 12: "LHip", 13: "LKnee", 14: "LAnkle",
                              15: "REye", 16: "LEye", 17: "REar", 18: "LEar", 19: "LBigToe",
                              20: "LSmallToe", 21: "LHeel", 22: "RBigToe", 23: "RSmallToe", 24: "RHeel",
                              25: "Background"}

        POSE_PAIRS_BODY_25 = [[5, 18], [2, 17]] # [0, 2], [0, 5],

        frame_man = output_keypoints(frame=cv_img, proto_file=protoFile_body_25, weights_file=weightsFile_body_25,
                                     threshold=0.1, model_name='', BODY_PARTS=BODY_PARTS_BODY_25)
        img = output_keypoints_with_lines(POSE_PAIRS=POSE_PAIRS_BODY_25, frame=frame_man)

        # convert back to pil image
        im_pil = Image.fromarray(img)

        # 저장
        buffer = BytesIO()
        im_pil.save(buffer, format='png')
        image_png = buffer.getvalue()

        self.image.save(str(self.image), ContentFile(image_png), save=False)

        super().save(*args, **kwargs)

poseapp/forms.py
from django.forms import ModelForm

from poseapp.models import Pose


class PoseCreationForm(ModelForm):
    class Meta:
        model = Pose
        fields = ['image']

poseapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, DetailView

from poseapp.forms import PoseCreationForm
from poseapp.models import Pose


def hello_world(request):
    return render(request, 'base.html')


class PoseCreateView(CreateView):
    model = Pose
    form_class = PoseCreationForm
    template_name = 'poseapp/create.html'

    def get_success_url(self):
        return reverse('poseapp:detail', kwargs={'pk': self.object.pk})


class PoseDetailView(DetailView):
    model = Pose
    context_object_name = 'target_pose'
    template_name = 'poseapp/detail.html'

poseapp/templates/poseapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Select Image</h4>
    </div>
    <div>
        <form action="{% url 'poseapp:create' %}"
              enctype="multipart/form-data"
              method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
 </div>

{% endblock %}

poseapp/templates/poseapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Result of a diagnosis</h4>
    </div>
    <div>
        <img style="width: 70%;" src="{{ target_pose.image.url }}" alt="">
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">

{% include 'header.html' %}

<hr>

{% block content %}
{% endblock %}

<hr>

{%  include 'footer.html' %}

</body>

</html>

templates/footer.html
<div style="text-align: center">

    <div class="Tutleneck_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div class="Tutleneck_footer_logo">
        <h5>Diagnose</h5>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>testing</title>

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">

    <div class="Turtleneck_header_logo">
        <h1>Are You Turtle-Necked?</h1>
    </div>
    <div class="Turtleneck_header_button">
{#        <a href="{% url 'poseapp:posecheck' %}">#}
            <span>
                Diagnose
            </span>
        </a>
    </div>

</div>